name: Upload core dumps
description: Uploads generated core.* files as a build artifact.

runs:
  using: composite
  steps:
    - name: Upload core dumps
      uses: actions/upload-artifact@v3
      with:
        name: core_dumps
        path: core*
        if-no-files-found: ignore
    - name: Remove core dumps
      shell: bash
      run: rm -rf core*
