[package]
name = "mc-core-types"
version = "2.0.0"
authors = ["MobileCoin"]
edition = "2021"
description = "MobileCoin Core Types"
readme = "README.md"

[features]
serde = ["dep:serde", "mc-crypto-keys/serde"]
prost = ["dep:prost", "mc-crypto-keys/prost" ]
alloc = ["mc-crypto-keys/alloc"]
default = ["serde", "prost"]

[dependencies]
# External dependencies
curve25519-dalek = { version = "4.0.0-pre.2", default-features = false }
serde = { version = "1.0.144", optional = true, default-features = false, features = [ "derive" ] }
prost = { version = "0.11.2", optional = true, default-features = false }
zeroize = { version = "1.5", default-features = false }

# MobileCoin dependencies
mc-crypto-keys = { path = "../../crypto/keys", default-features = false }
