name: Check dirty git
description: Check the git status of the current directory, and raise an error if there are uncommitted changes.

runs:
  using: composite
  steps:
    - name: Checking dirty git
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "repo is dirty"
          git status
          exit 1
        fi
